#!/usr/bin/env node
/**
 * Generates src/components/journey/road-paths.ts.
 *
 * The road is authored as control points in a per-stage coordinate space
 * (100 units wide, 100 units tall per stage) and smoothed into cubic beziers
 * with a Catmull-Rom spline, so curvature is continuous and the figure
 * travelling the motion path never jerks at a segment boundary.
 *
 * Re-run this whenever a stage is added:  node scripts/generate-road.mjs
 */
import { writeFileSync } from 'node:fs';

/**
 * Stage 1 is deliberately empty above y=88: the hero needs heavy negative
 * space and the road enters at its lower left, under the type rather than
 * through it.
 */
const DESKTOP = [
  // The journey reserves a road lane down its right hand side (see the
  // .journey .shell padding rule), so the road never has to dodge the copy
  // and the copy never has to dodge the road.
  [4, 88], [26, 94], [52, 99], [74, 105], [88, 116],
  [94, 138], [88, 164], [84, 190],
  [88, 216], [94, 242], [95, 270],
  [89, 296], [84, 322], [86, 350],
  [92, 376], [95, 402], [90, 428],
  [85, 454], [84, 480], [88, 506],
  [93, 532], [95, 560], [90, 586],
  [85, 612], [84, 638], [88, 664], [91, 692],
];

const MOBILE = [
  [8, 90], [30, 100], [56, 110], [78, 122], [90, 142],
  [94, 178], [89, 214], [91, 250],
  [95, 286], [92, 322], [88, 358],
  [90, 394], [95, 430], [93, 466],
  [89, 502], [91, 538], [95, 574],
  [92, 610], [88, 646], [91, 692],
];

const STAGES = 7; // hero, scope, gap, impact, field report, branch, join.

function spline(pts) {
  let d = `M ${pts[0][0].toFixed(2)} ${pts[0][1].toFixed(2)}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[i - 1] ?? pts[0];
    const p1 = pts[i];
    const p2 = pts[i + 1];
    const p3 = pts[i + 2] ?? pts[pts.length - 1];
    const c1 = [p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6];
    const c2 = [p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6];
    d += ` C ${c1[0].toFixed(2)} ${c1[1].toFixed(2)}, ${c2[0].toFixed(2)} ${c2[1].toFixed(2)}, ${p2[0].toFixed(2)} ${p2[1].toFixed(2)}`;
  }
  return d;
}

const out = `/**
 * GENERATED by scripts/generate-road.mjs. Do not edit by hand.
 * Edit the control points in that script and re-run it.
 *
 * Coordinate space is 100 wide by ${STAGES * 100} tall, one hundred units per
 * stage. The SVG uses preserveAspectRatio="none" to stretch to the journey
 * container, and vector-effect="non-scaling-stroke" so the road keeps a
 * constant weight despite that stretch.
 */

export const ROAD_STAGES = ${STAGES};
export const ROAD_VIEWBOX = '0 0 100 ${STAGES * 100}';

export const ROAD_DESKTOP =
  '${spline(DESKTOP)}';

export const ROAD_MOBILE =
  '${spline(MOBILE)}';
`;

writeFileSync(new URL('../src/components/journey/road-paths.ts', import.meta.url), out);
console.log(`road-paths.ts generated for ${STAGES} stages`);
